apiVersion: apiextenstions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: copyrator.isurusiri.com
spec:
  group: isurusiri.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: copyrators
    singular: copyrator
    kind: CopyratorRule
    shortNames:
    - copyr
  validation:
    openAPIV3Schema:
      type: object
      properties:
        ruleType:
          type: string
        namespaces:
          type: array
          items:
            type: string
        selector:
          type: string